### PR TITLE
feat: update iptables image

### PR DESCRIPTION
**Pull request by frezbo**
Update iptables image to bookworm.

### CODE REVIEW

**Review by smira — APPROVED** [review]
I wonder if that would allow now to install updated ceph

**Comment by frezbo** [comment]
> I wonder if that would allow now to install updated ceph

still broken :sweat_smile: 

```bash
# # apt-get clean \
  && clean-install ceph-common> 
Hit:1 http://deb.debian.org/debian bookworm InRelease                                                         
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                                                 
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Get:4 https://download.ceph.com/debian-pacific bullseye InRelease [8565 B]
Get:5 https://download.ceph.com/debian-pacific bullseye/main arm64 Packages [3071 B]                                                                                                          
Fetched 11.6 kB in 11s (1033 B/s)                                                                                                                                                             
Reading package lists... Done
W: https://download.ceph.com/debian-pacific/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ceph-common : Depends: python3-ceph-argparse (= 16.2.11+ds-2) but 16.2.13-1~bpo11+1 is to be installed
               Depends: python3-ceph-common (< 16.2.11+ds-2.1~) but 16.2.13-1~bpo11+1 is to be installed
               Depends: python3-cephfs (= 16.2.11+ds-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by frezbo** [comment]
ahh well both amd64 and arm64 is broken

**Comment by smira** [comment]
> Get:4 https://download.ceph.com/debian-pacific bullseye InRelease [8565 B]
> Get:5 https://download.ceph.com/debian-pacific bullseye/main arm64 Packages [3071 B]                                                                                                          
 

bullseye?

**Comment by frezbo** [comment]
> > Get:4 https://download.ceph.com/debian-pacific bullseye InRelease [8565 B]
> > Get:5 https://download.ceph.com/debian-pacific bullseye/main arm64 Packages [3071 B]
> 
> bullseye?

there's no ceph repo for bookworm

**Comment by frezbo** [comment]
I wonder if we should just use what debian provides

**Comment by smira** [comment]
> I wonder if we should just use what debian provides

idk, it could be now more up to date... but usually it's very outdated

**Pull request merged**
