### PR TITLE
chore: bump kubelet to v1.24.0

### PR DESCRIPTION
**Pull request by frezbo**
Bump kubelet to v1.24.0

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Comment by frezbo** [comment]
@smira should we bump this: https://github.com/siderolabs/kubelet/blob/master/Dockerfile#L31=

Seems `us.gcr.io/k8s-artifacts-prod/build-image/debian-iptables:bullseye-v1.3.0` is available

**Comment by smira** [comment]
Yep, we should, if there's a new one!

**Review by smira — APPROVED** [review]

**Pull request merged**
