### PR TITLE
chore: update kubelet to v1.25.0-alpha.0

### PR DESCRIPTION
**Pull request by frezbo**
Update kubelet to v1.25.0-alpha.0

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Comment by smira** [comment]
I would say we shouldn't do that until we go into Talos 1.2.0 release cycle. We can bump the kubelet, but most probably it won't see any use until we cut stable 1.2.0 branch.

**Comment by smira** [comment]
Looks like 1.25 going to be released late August, should be great time for Talos 1.2.0: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25#timeline

**Comment by frezbo** [comment]
> I would say we shouldn't do that until we go into Talos 1.2.0 release cycle. We can bump the kubelet, but most probably it won't see any use until we cut stable 1.2.0 branch.

yup, will keep the PR here, and not merge now

**Pull request closed without merging**
